version: 0.1
phases: 
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "docker login --username=\"mathandotcom\" --password=\"mm070676\""
  build:
    commands:
      - echo build Docker image on `date`
      - cd src
      - docker build -t mycontainer:latest .