version: 0.1
phases: 
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "docker login --username=\"mathandotcom\" --password=\"mm070676\""
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t mycontainer ."
      - "docker tag mycontainer mathandotcom/samplenode:v2"
      
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push mathandotcom/samplenode:v2"